RazorViewsAssignment/Models/CityWeather.cs
namespace RazorViewsAssignment.Models
{
	public class CityWeather
	{
		public string? CityUniqueCode { get; set; }

		public string? CityName { get; set; }

		public DateTime? DateAndTime { get; set; }

		public int? TemperatureFahrenheit { get; set; }
	}
}

RazorViewsAssignment/Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using RazorViewsAssignment.Models;

namespace RazorViewsAssignment.Controllers
{
	public class WeatherController : Controller
	{
		[Route("/")]
		public IActionResult Weather()
		{
			var weatherData = new List<CityWeather>
			{
				new CityWeather() { CityUniqueCode = "LDN", CityName = "London", DateAndTime = Convert.ToDateTime("2030-01-01 8:00:00 AM"),  TemperatureFahrenheit = 33 },
				new CityWeather() { CityUniqueCode = "NYC", CityName = "New York City", DateAndTime = Convert.ToDateTime("2030-01-01 3:00:00 AM"),  TemperatureFahrenheit = 60 },
				new CityWeather() { CityUniqueCode = "PAR", CityName = "Paris", DateAndTime = Convert.ToDateTime("2030-01-01 9:00:00 AM"),  TemperatureFahrenheit = 82 }
			};
			return View(weatherData);
		}

		[Route("/weather/{cityCode}")]
		public IActionResult City(string cityCode) 
		{
			var weatherData = new List<CityWeather>
			{
				new CityWeather() { CityUniqueCode = "LDN", CityName = "London", DateAndTime = Convert.ToDateTime("2030-01-01 8:00 AM"),  TemperatureFahrenheit = 33 },
				new CityWeather() { CityUniqueCode = "NYC", CityName = "New York City", DateAndTime = Convert.ToDateTime("2030-01-01 3:00 AM"),  TemperatureFahrenheit = 60 },
				new CityWeather() { CityUniqueCode = "PAR", CityName = "Paris", DateAndTime = Convert.ToDateTime("2030-01-01 9:00 AM"),  TemperatureFahrenheit = 82 }
			};

			var city = weatherData.FirstOrDefault(w => w.CityUniqueCode == cityCode);
			if (city != default) 
			{
				return View(city);
			}
			return View("Error", cityCode);
		}
	}
}

RazorViewsAssignment/ViewComponents/CityViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RazorViewsAssignment.Models;

namespace RazorViewsAssignment.ViewComponents
{
	public class CityViewComponent : ViewComponent
	{
		public async Task<IViewComponentResult> InvokeAsync(CityWeather weatherInCity) 
		{
			return View(weatherInCity);
		}
	}
}

RazorViewsAssignment/Views/Shared/Components/City/Default.cshtml
@model CityWeather;

@{
	string GetColorClass(int? temperature)
	{
		if (temperature <= 44)
		{
			return "blue-back";
		}
		else if (temperature > 44 && temperature <= 74)
		{
			return "green-back";
		}
		return "orange-back";
	}
}

<div class="box @GetColorClass(Model.TemperatureFahrenheit)">
	<div class="cityDetailsBlock">
		<h2>@Model.CityName</h2>
		<h3>@Model.DateAndTime?.ToString("hh:mm tt", CultureInfo.InvariantCulture)</h3>
		<a href="~/weather/@Model.CityUniqueCode">Details</a>
	</div>

	<div class="temperatureDetailsBlock">
		<h2>@Model.TemperatureFahrenheit <sup class="text-grey">°F</sup></h2>
	</div>
</div>

RazorViewsAssignment/Views/Shared/_LayoutView.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>@ViewBag.Title</title>
	<meta charset="utf-8">
	<link href="~/Stylesheet.css" rel="stylesheet" />
</head>
<body>
	<div class="page-content">
			@RenderSection("heading", false)
			@RenderBody()
	</div>
</body>
</html>

RazorViewsAssignment/Views/Weather/City.cshtml
@model CityWeather
@{
	ViewBag.Title = $"{@Model.CityName} Weather";
}

<div class="container">
	<div class="box">
		<div class="cityDetailsBlock">
			<h2>@Model.CityName</h2>
			<h3 class="text-grey">@Model.DateAndTime?.ToString("dd MMM yyyy", CultureInfo.InvariantCulture)</h3>
			<h3 class="text-grey">@Model.DateAndTime?.ToString("hh:mm tt", CultureInfo.InvariantCulture)</h3>
		</div>

		<div class="temperatureDetailsBlock">
			<h2>@Model.TemperatureFahrenheit <sup class="text-grey">°F</sup></h2>
		</div>
	</div>
	<div class="footer">
		<a href="~/">Back to Weather Home Page</a>
	</div>
</div>

@section heading{
	<h1>Weather in @Model.CityName</h1>
}

RazorViewsAssignment/Views/Weather/Weather.cshtml
@model IEnumerable<CityWeather>

@{
	ViewBag.Title = $"Weather";
}

<div class="list-container">
	@foreach (CityWeather cityWeather in Model)
	{
		<vc:city weather-in-city=cityWeather></vc:city>
	}
</div>

@section heading{
	<h1>Weather</h1>
}